const now = new Date();
const daysAgo = (n) => new Date(now - n * 86400000);

export const MOCK_BARANGAYS = [
  {
    id: "brgy-balagbag-001",
    name: "Balagbag",
    address: "Balagbag, Cuenca, Batangas",
    contactNumber: "0917-111-0001",
    email: "balagbag@cuenca.gov.ph",
    orgChartVMVB: [
      { name: "Juan dela Cruz", position: "Barangay Captain" },
      { name: "Maria Santos",   position: "Kagawad" },
    ],
    orgChartSecretariat: [
      { name: "Ana Gomez", position: "Barangay Secretary" },
    ],
    committees: [
      { memberName: "Maria Santos", committees: "Finance, Health" },
    ],
  },
  {
    id: "brgy-pob1-001",
    name: "Barangay 1 (Pob.)",
    address: "Barangay 1, Cuenca, Batangas",
    contactNumber: "0917-111-0002",
    email: "pob1@cuenca.gov.ph",
    orgChartVMVB: [
      { name: "Pedro Reyes", position: "Barangay Captain" },
    ],
    orgChartSecretariat: [
      { name: "Lito Ramos", position: "Barangay Secretary" },
    ],
    committees: [],
  },
  {
    id: "brgy-dita-001",
    name: "Dita",
    address: "Dita, Cuenca, Batangas",
    contactNumber: "0917-111-0014",
    email: "dita@cuenca.gov.ph",
    orgChartVMVB: [
      { name: "Rosa Magtibay", position: "Barangay Captain" },
    ],
    orgChartSecretariat: [
      { name: "Mely Cruz", position: "Barangay Secretary" },
    ],
    committees: [],
  },
];

export const MOCK_DOCUMENTS = [
  {
    id: "doc-001",
    fileName: "BALAGBAG_RESOLUTION_20250301.pdf",
    originalName: "resolution_march.pdf",
    fileUrl: "#",
    filePath: "documents/brgy-balagbag-001/resolution/doc-001.pdf",
    fileSize: 204800,
    fileType: "application/pdf",
    category: "resolution",
    description: "Resolution No. 2025-03 adopting the barangay peace and order plan.",
    barangayId: "brgy-balagbag-001",
    barangayName: "Balagbag",
    uploadedBy: "Brgy. Secretary - Balagbag",
    uploadedById: "brgy-balagbag-001",
    status: "Approved",
    reviewNote: "Looks good. Approved for filing.",
    uploadedAt: daysAgo(2),
    reviewedAt: daysAgo(1),
  },
  {
    id: "doc-002",
    fileName: "BALAGBAG_REPORT_20250310.pdf",
    originalName: "monthly_report.pdf",
    fileUrl: "#",
    filePath: "documents/brgy-balagbag-001/report/doc-002.pdf",
    fileSize: 512000,
    fileType: "application/pdf",
    category: "report",
    description: "Monthly accomplishment report for March 2025.",
    barangayId: "brgy-balagbag-001",
    barangayName: "Balagbag",
    uploadedBy: "Brgy. Secretary - Balagbag",
    uploadedById: "brgy-balagbag-001",
    status: "Pending",
    reviewNote: "",
    uploadedAt: daysAgo(1),
    reviewedAt: null,
  },
  {
    id: "doc-003",
    fileName: "POB1_ORDINANCE_20250305.pdf",
    originalName: "ordinance_005.pdf",
    fileUrl: "#",
    filePath: "documents/brgy-pob1-001/ordinance/doc-003.pdf",
    fileSize: 307200,
    fileType: "application/pdf",
    category: "ordinance",
    description: "Barangay Ordinance No. 005 on solid waste management.",
    barangayId: "brgy-pob1-001",
    barangayName: "Barangay 1 (Pob.)",
    uploadedBy: "Brgy. Secretary - Barangay 1",
    uploadedById: "brgy-pob1-001",
    status: "Reviewed",
    reviewNote: "Under review by committee.",
    uploadedAt: daysAgo(5),
    reviewedAt: daysAgo(3),
  },
  {
    id: "doc-004",
    fileName: "DITA_BUDGET_20250312.pdf",
    originalName: "budget_proposal_q2.pdf",
    fileUrl: "#",
    filePath: "documents/brgy-dita-001/budget/doc-004.pdf",
    fileSize: 1048576,
    fileType: "application/pdf",
    category: "budget",
    description: "Q2 Budget Proposal for Dita Barangay.",
    barangayId: "brgy-dita-001",
    barangayName: "Dita",
    uploadedBy: "Brgy. Secretary - Dita",
    uploadedById: "brgy-dita-001",
    status: "For Revision",
    reviewNote: "Please revise the expense breakdown on page 3.",
    uploadedAt: daysAgo(7),
    reviewedAt: daysAgo(4),
  },
];

export const MOCK_ACTIVITY_LOGS = [
  {
    id: "log-001",
    action: "UPLOAD",
    description: "Uploaded document: BALAGBAG_RESOLUTION_20250301.pdf",
    barangayName: "Balagbag",
    userName: "Brgy. Secretary - Balagbag",
    timestamp: daysAgo(2),
  },
  {
    id: "log-002",
    action: "STATUS_CHANGE",
    description: 'Changed status of "BALAGBAG_RESOLUTION_20250301.pdf" to Approved',
    barangayName: "Balagbag",
    userName: "SB Admin",
    timestamp: daysAgo(1),
  },
  {
    id: "log-003",
    action: "UPLOAD",
    description: "Uploaded document: POB1_ORDINANCE_20250305.pdf",
    barangayName: "Barangay 1 (Pob.)",
    userName: "Brgy. Secretary - Barangay 1",
    timestamp: daysAgo(5),
  },
  {
    id: "log-004",
    action: "STATUS_CHANGE",
    description: 'Changed status of "DITA_BUDGET_20250312.pdf" to For Revision',
    barangayName: "Dita",
    userName: "SB Admin",
    timestamp: daysAgo(4),
  },
];